// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: saludo.proto
#ifndef GRPC_saludo_2eproto__INCLUDED
#define GRPC_saludo_2eproto__INCLUDED

#include "saludo.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace saludo {

class Saludo final {
 public:
  static constexpr char const* service_full_name() {
    return "saludo.Saludo";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::saludo::Respuesta* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::saludo::Respuesta>> AsyncDiHola(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::saludo::Respuesta>>(AsyncDiHolaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::saludo::Respuesta>> PrepareAsyncDiHola(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::saludo::Respuesta>>(PrepareAsyncDiHolaRaw(context, request, cq));
    }
    // Método RPC
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Método RPC
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::saludo::Respuesta>* AsyncDiHolaRaw(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::saludo::Respuesta>* PrepareAsyncDiHolaRaw(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::saludo::Respuesta* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::saludo::Respuesta>> AsyncDiHola(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::saludo::Respuesta>>(AsyncDiHolaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::saludo::Respuesta>> PrepareAsyncDiHola(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::saludo::Respuesta>>(PrepareAsyncDiHolaRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response, std::function<void(::grpc::Status)>) override;
      void DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::saludo::Respuesta>* AsyncDiHolaRaw(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::saludo::Respuesta>* PrepareAsyncDiHolaRaw(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DiHola_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DiHola(::grpc::ServerContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response);
    // Método RPC
  };
  template <class BaseClass>
  class WithAsyncMethod_DiHola : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DiHola() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DiHola() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DiHola(::grpc::ServerContext* /*context*/, const ::saludo::Solicitud* /*request*/, ::saludo::Respuesta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDiHola(::grpc::ServerContext* context, ::saludo::Solicitud* request, ::grpc::ServerAsyncResponseWriter< ::saludo::Respuesta>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DiHola<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DiHola : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DiHola() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::saludo::Solicitud, ::saludo::Respuesta>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response) { return this->DiHola(context, request, response); }));}
    void SetMessageAllocatorFor_DiHola(
        ::grpc::MessageAllocator< ::saludo::Solicitud, ::saludo::Respuesta>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::saludo::Solicitud, ::saludo::Respuesta>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DiHola() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DiHola(::grpc::ServerContext* /*context*/, const ::saludo::Solicitud* /*request*/, ::saludo::Respuesta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DiHola(
      ::grpc::CallbackServerContext* /*context*/, const ::saludo::Solicitud* /*request*/, ::saludo::Respuesta* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_DiHola<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DiHola : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DiHola() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DiHola() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DiHola(::grpc::ServerContext* /*context*/, const ::saludo::Solicitud* /*request*/, ::saludo::Respuesta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DiHola : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DiHola() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DiHola() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DiHola(::grpc::ServerContext* /*context*/, const ::saludo::Solicitud* /*request*/, ::saludo::Respuesta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDiHola(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DiHola : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DiHola() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DiHola(context, request, response); }));
    }
    ~WithRawCallbackMethod_DiHola() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DiHola(::grpc::ServerContext* /*context*/, const ::saludo::Solicitud* /*request*/, ::saludo::Respuesta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DiHola(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DiHola : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DiHola() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::saludo::Solicitud, ::saludo::Respuesta>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::saludo::Solicitud, ::saludo::Respuesta>* streamer) {
                       return this->StreamedDiHola(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DiHola() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DiHola(::grpc::ServerContext* /*context*/, const ::saludo::Solicitud* /*request*/, ::saludo::Respuesta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDiHola(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::saludo::Solicitud,::saludo::Respuesta>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DiHola<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DiHola<Service > StreamedService;
};
// Definición del servicio gRPC

}  // namespace saludo


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_saludo_2eproto__INCLUDED
