// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: saludo.proto

#include "saludo.pb.h"
#include "saludo.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace saludo {

static const char* Saludo_method_names[] = {
  "/saludo.Saludo/DiHola",
};

std::unique_ptr< Saludo::Stub> Saludo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Saludo::Stub> stub(new Saludo::Stub(channel, options));
  return stub;
}

Saludo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_DiHola_(Saludo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Saludo::Stub::DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::saludo::Respuesta* response) {
  return ::grpc::internal::BlockingUnaryCall< ::saludo::Solicitud, ::saludo::Respuesta, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DiHola_, context, request, response);
}

void Saludo::Stub::async::DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::saludo::Solicitud, ::saludo::Respuesta, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DiHola_, context, request, response, std::move(f));
}

void Saludo::Stub::async::DiHola(::grpc::ClientContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DiHola_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::saludo::Respuesta>* Saludo::Stub::PrepareAsyncDiHolaRaw(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::saludo::Respuesta, ::saludo::Solicitud, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DiHola_, context, request);
}

::grpc::ClientAsyncResponseReader< ::saludo::Respuesta>* Saludo::Stub::AsyncDiHolaRaw(::grpc::ClientContext* context, const ::saludo::Solicitud& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDiHolaRaw(context, request, cq);
  result->StartCall();
  return result;
}

Saludo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Saludo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Saludo::Service, ::saludo::Solicitud, ::saludo::Respuesta, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Saludo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::saludo::Solicitud* req,
             ::saludo::Respuesta* resp) {
               return service->DiHola(ctx, req, resp);
             }, this)));
}

Saludo::Service::~Service() {
}

::grpc::Status Saludo::Service::DiHola(::grpc::ServerContext* context, const ::saludo::Solicitud* request, ::saludo::Respuesta* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace saludo

