# quitamos esta linea: - ./empresa3_pg.sql:/docker-entrypoint-initdb.d/empresa3_pg.sql, si fuera de texto si se puede hacer como en mysql
# es un backup binario y hay que restaurar con un comando pgrestore: 
# Desde fuera lanzar este comando: docker exec -i postgres_dev pg_restore -U antonio -d empresa3 < empresa3_pg.sql

services:
  postgres_dev:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment: 
      POSTGRES_DB: empresa3
      POSTGRES_USER: antonio
      POSTGRES_PASSWORD: antonio
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      
      
volumes:
  pg_data:
