# restart: always, si el contenedor se detiene docker lo vuelve a levantar

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./empresa3_mysql.sql:/docker-entrypoint-initdb.d/empresa3_mysql.sql
    
volumes:
  mysql_data:
      