# Base de datos PostGres:

services:
  postgres_dev:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_DB: empresa3
      POSTGRES_USER: antonio
      POSTGRES_PASSWORD: antonio
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      
volumes:
  pg_data: