# restart: always si el contenedor se detiene docker lo volvera a levantar.
# 3307 del host y 3306 del contenedor
# mysql_data:/var/lib/mysql  crea un volumen para almacenar los datos del mysql, persiste aunque se borre el contenedor
# ./empresa3_mysql.sql:/docker-entrypoint-initdb.d/empresa3_mysql.sql  monta el archivo desde tu maquina dentro del contenedor.
# MySQL ejecuta automáticamente cualquier script dentro de /docker-entrypoint-initdb.d -> se hace para importar el backup
# abajo se declara el volumen

# DATOS DE CONEXION:
# HOST: localhost
# PUERTO: 3307
# USER: daniel
# PASS: 1234
# BD: empresa3

services:
  mysql:
    image: mysql:8.0
    container_name : mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: empresa3
      MYSQL_USER: daniel
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./empresa3_mysql.sql:/docker-entrypoint-initdb.d/empresa3_mysql.sql

volumes:
  mysql_data:
