// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: saludo.proto
// Protobuf C++ Version: 5.29.5

#include "saludo.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace saludo {

inline constexpr Solicitud::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : nombre_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Solicitud::Solicitud(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SolicitudDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SolicitudDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SolicitudDefaultTypeInternal() {}
  union {
    Solicitud _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SolicitudDefaultTypeInternal _Solicitud_default_instance_;

inline constexpr Respuesta::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : mensaje_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Respuesta::Respuesta(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RespuestaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespuestaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespuestaDefaultTypeInternal() {}
  union {
    Respuesta _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespuestaDefaultTypeInternal _Respuesta_default_instance_;
}  // namespace saludo
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_saludo_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_saludo_2eproto = nullptr;
const ::uint32_t
    TableStruct_saludo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::saludo::Solicitud, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::saludo::Solicitud, _impl_.nombre_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::saludo::Respuesta, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::saludo::Respuesta, _impl_.mensaje_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::saludo::Solicitud)},
        {9, -1, -1, sizeof(::saludo::Respuesta)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::saludo::_Solicitud_default_instance_._instance,
    &::saludo::_Respuesta_default_instance_._instance,
};
const char descriptor_table_protodef_saludo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014saludo.proto\022\006saludo\"\033\n\tSolicitud\022\016\n\006n"
    "ombre\030\001 \001(\t\"\034\n\tRespuesta\022\017\n\007mensaje\030\001 \001("
    "\t28\n\006Saludo\022.\n\006DiHola\022\021.saludo.Solicitud"
    "\032\021.saludo.Respuestab\006proto3"
};
static ::absl::once_flag descriptor_table_saludo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_saludo_2eproto = {
    false,
    false,
    147,
    descriptor_table_protodef_saludo_2eproto,
    "saludo.proto",
    &descriptor_table_saludo_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_saludo_2eproto::offsets,
    file_level_enum_descriptors_saludo_2eproto,
    file_level_service_descriptors_saludo_2eproto,
};
namespace saludo {
// ===================================================================

class Solicitud::_Internal {
 public:
};

Solicitud::Solicitud(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:saludo.Solicitud)
}
inline PROTOBUF_NDEBUG_INLINE Solicitud::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::saludo::Solicitud& from_msg)
      : nombre_(arena, from.nombre_),
        _cached_size_{0} {}

Solicitud::Solicitud(
    ::google::protobuf::Arena* arena,
    const Solicitud& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Solicitud* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:saludo.Solicitud)
}
inline PROTOBUF_NDEBUG_INLINE Solicitud::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : nombre_(arena),
        _cached_size_{0} {}

inline void Solicitud::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Solicitud::~Solicitud() {
  // @@protoc_insertion_point(destructor:saludo.Solicitud)
  SharedDtor(*this);
}
inline void Solicitud::SharedDtor(MessageLite& self) {
  Solicitud& this_ = static_cast<Solicitud&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nombre_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Solicitud::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Solicitud(arena);
}
constexpr auto Solicitud::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Solicitud),
                                            alignof(Solicitud));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Solicitud::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Solicitud_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Solicitud::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Solicitud>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Solicitud::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Solicitud>(), &Solicitud::ByteSizeLong,
            &Solicitud::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Solicitud, _impl_._cached_size_),
        false,
    },
    &Solicitud::kDescriptorMethods,
    &descriptor_table_saludo_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Solicitud::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 31, 2> Solicitud::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::saludo::Solicitud>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string nombre = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Solicitud, _impl_.nombre_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string nombre = 1;
    {PROTOBUF_FIELD_OFFSET(Solicitud, _impl_.nombre_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\6\0\0\0\0\0\0"
    "saludo.Solicitud"
    "nombre"
  }},
};

PROTOBUF_NOINLINE void Solicitud::Clear() {
// @@protoc_insertion_point(message_clear_start:saludo.Solicitud)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nombre_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Solicitud::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Solicitud& this_ = static_cast<const Solicitud&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Solicitud::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Solicitud& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:saludo.Solicitud)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string nombre = 1;
          if (!this_._internal_nombre().empty()) {
            const std::string& _s = this_._internal_nombre();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "saludo.Solicitud.nombre");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:saludo.Solicitud)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Solicitud::ByteSizeLong(const MessageLite& base) {
          const Solicitud& this_ = static_cast<const Solicitud&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Solicitud::ByteSizeLong() const {
          const Solicitud& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:saludo.Solicitud)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string nombre = 1;
            if (!this_._internal_nombre().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_nombre());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Solicitud::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Solicitud*>(&to_msg);
  auto& from = static_cast<const Solicitud&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:saludo.Solicitud)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nombre().empty()) {
    _this->_internal_set_nombre(from._internal_nombre());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Solicitud::CopyFrom(const Solicitud& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:saludo.Solicitud)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Solicitud::InternalSwap(Solicitud* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nombre_, &other->_impl_.nombre_, arena);
}

::google::protobuf::Metadata Solicitud::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Respuesta::_Internal {
 public:
};

Respuesta::Respuesta(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:saludo.Respuesta)
}
inline PROTOBUF_NDEBUG_INLINE Respuesta::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::saludo::Respuesta& from_msg)
      : mensaje_(arena, from.mensaje_),
        _cached_size_{0} {}

Respuesta::Respuesta(
    ::google::protobuf::Arena* arena,
    const Respuesta& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Respuesta* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:saludo.Respuesta)
}
inline PROTOBUF_NDEBUG_INLINE Respuesta::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : mensaje_(arena),
        _cached_size_{0} {}

inline void Respuesta::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Respuesta::~Respuesta() {
  // @@protoc_insertion_point(destructor:saludo.Respuesta)
  SharedDtor(*this);
}
inline void Respuesta::SharedDtor(MessageLite& self) {
  Respuesta& this_ = static_cast<Respuesta&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.mensaje_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Respuesta::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Respuesta(arena);
}
constexpr auto Respuesta::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Respuesta),
                                            alignof(Respuesta));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Respuesta::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Respuesta_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Respuesta::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Respuesta>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Respuesta::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Respuesta>(), &Respuesta::ByteSizeLong,
            &Respuesta::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Respuesta, _impl_._cached_size_),
        false,
    },
    &Respuesta::kDescriptorMethods,
    &descriptor_table_saludo_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Respuesta::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2> Respuesta::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::saludo::Respuesta>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string mensaje = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Respuesta, _impl_.mensaje_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string mensaje = 1;
    {PROTOBUF_FIELD_OFFSET(Respuesta, _impl_.mensaje_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\7\0\0\0\0\0\0"
    "saludo.Respuesta"
    "mensaje"
  }},
};

PROTOBUF_NOINLINE void Respuesta::Clear() {
// @@protoc_insertion_point(message_clear_start:saludo.Respuesta)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mensaje_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Respuesta::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Respuesta& this_ = static_cast<const Respuesta&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Respuesta::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Respuesta& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:saludo.Respuesta)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string mensaje = 1;
          if (!this_._internal_mensaje().empty()) {
            const std::string& _s = this_._internal_mensaje();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "saludo.Respuesta.mensaje");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:saludo.Respuesta)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Respuesta::ByteSizeLong(const MessageLite& base) {
          const Respuesta& this_ = static_cast<const Respuesta&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Respuesta::ByteSizeLong() const {
          const Respuesta& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:saludo.Respuesta)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string mensaje = 1;
            if (!this_._internal_mensaje().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_mensaje());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Respuesta::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Respuesta*>(&to_msg);
  auto& from = static_cast<const Respuesta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:saludo.Respuesta)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_mensaje().empty()) {
    _this->_internal_set_mensaje(from._internal_mensaje());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Respuesta::CopyFrom(const Respuesta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:saludo.Respuesta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Respuesta::InternalSwap(Respuesta* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.mensaje_, &other->_impl_.mensaje_, arena);
}

::google::protobuf::Metadata Respuesta::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace saludo
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_saludo_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
