# Base de datos PostGres:

services:
  postgres_dev:
    image: postgres:16
    container_name:  postgres_dev
    restart:  always
    enviroment:
      POSTGRES_DB: empresa3
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pg_data: /var/lib/postgresql/data
      
volumes:
  pg_data: